### ISSUE TITLE
1.2 - Realizar a busca no banco de dados da tabela "typeWeakeness"

### ISSUE THREAD

**Issue by Leandrowisky** [mcpereira7/pi1#2]
Utilizar o objeto da tarefa 1.0

Criar nova Classe dentro da pasta DAO com nome sugestivo para a tabela.

Criar um método(função) que receberá o Tipo do pokémon atacante e defensor, retornando a força do ataque realizado, usar double pois terá casa decimal.
Ficará parecido com isso: static double atkForce(int typeAtk, int typeDef)

Ele irá fazer o select: "SELECT * FROM typeWeakeness WHERE typeAtk = ? and typeDef = ?"

executar o select e retornar o valor do campo "power" presente na tabela.

**Comment by mcpereira7** [comment]
Vinicius criou essa classe já.
