### ISSUE TITLE
2.0 - Criar a tabela "moveList" no MySQL

### ISSUE THREAD

**Issue by Leandrowisky** [mcpereira7/pi1#3]
Criar a tabela "moveList" e preencher os dados do Excel anexado.
[Move_list_and_pokemon_moves.xlsx](https://github.com/mcpereira7/pi1/files/1015780/Move_list_and_pokemon_moves.xlsx)

OBS: o campo "type" deverá ser o ID do tipo e não a String.

**Comment by mcpereira7** [comment]
Tabela criada e populada
