### ISSUE TITLE
3.0 - Criar tabela "pokemonMoves" no mySQL

### ISSUE THREAD

**Issue by Leandrowisky** [mcpereira7/pi1#4]
Criar a tabela "pokemonMoves" no mySQL.
Preencher com as informações presentes no Excel anexado.
[Move_list_and_pokemon_moves.xlsx](https://github.com/mcpereira7/pi1/files/1015784/Move_list_and_pokemon_moves.xlsx)

**Comment by mcpereira7** [comment]
Concluído
