### ISSUE TITLE
1.0 - Criar a tabela "typeWeakeness" no mySQL.

### ISSUE THREAD

**Issue by Leandrowisky** [mcpereira7/pi1#5]
Criar a tabela "typeWeakeness" no mySQL.
Preencher com as informações do Excel anexado.
[PokemonBattle.xlsx](https://github.com/mcpereira7/pi1/files/1015788/PokemonBattle.xlsx)

**Comment by mcpereira7** [comment]
Tabela Criada, dados já no GIT
